#ifndef OSCILLATOR_MACROS_H_
#define OSCILLATOR_MACROS_H_

#define PWM_DUTY_VALUE_MAX 1023
#define PWM_DUTY_VALUE_MIN 0

#define FIRST_QUADRANT_START_INDEX 0
#define SECOND_QUADRANT_START_INDEX 128
#define THIRD_QUADRANT_START_INDEX 256
#define FOURTH_QUADRANT_START_INDEX 384
#define FINAL_INDEX 511
#define TRIANGLE_MODE 0
#define SINE_MODE 1
#define SQUARE_MODE 2
#define NUMBER_OF_FREQUENCY_STEPS 643
#define FIRST_HALFCYCLE 0
#define SECOND_HALFCYCLE 1
#define FIRST_QUADRANT 0
#define SECOND_QUADRANT 1

#define TRIANGLE_MODE_ADC_THRESHOLD 1365 >> 5
#define SINE_MODE_ADC_THRESHOLD 2730 >> 5
#define SQUARE_MODE_ADC_THRESHOLD 4095 >> 5
#define WAVESHAPE_ADC_RESULT_INDEX 0
#define SPEED_ADC_RESULT_INDEX 1
#define DEPTH_ADC_RESULT_INDEX 2
#define SYMMETRY_ADC_RESULT_INDEX 3
#define PHASE_ADC_RESULT_INDEX 4

#define SINE_OR_TRIANGLE_WAVE_PREEMPTIVE_DELAY 50
#define SINE_OR_TRIANGLE_WAVE_TEMPO_PERCEIVED_APEX_INDEX 384 - SINE_OR_TRIANGLE_WAVE_PREEMPTIVE_DELAY
#define SQUARE_WAVE_TEMPO_APEX_INDEX 256
#define TEMPO_PULSE_LENGTH 32
#define SINE_OR_TRIANGLE_WAVE_TEMPO_PULSE_OFF_INDEX SINE_OR_TRIANGLE_WAVE_TEMPO_PERCEIVED_APEX_INDEX + TEMPO_PULSE_LENGTH
#define SQUARE_WAVE_TEMPO_PULSE_OFF_INDEX SQUARE_WAVE_TEMPO_APEX_INDEX + TEMPO_PULSE_LENGTH

#define HIGHEST_PRESCALER_TOP_SPEED_PERIOD 129

// Phase accumulator: fixed TIM16 configuration
// TIM16 input clock = 64 MHz / CKD_DIV4 = 16 MHz
// Interrupt rate = 16 MHz / PHASE_ACCUM_FIXED_PRESCALER / (PHASE_ACCUM_FIXED_ARR + 1)
//                = 16 MHz / 32 / 128 = 3906.25 Hz
#define PHASE_ACCUM_FIXED_PRESCALER           32    // TIM16 prescaler value (divides by 32)
#define PHASE_ACCUM_FIXED_PRESCALER_MINUS_ONE 31    // value written to PSC register
#define PHASE_ACCUM_FIXED_ARR                 127   // TIM16 auto-reload register (period = 128 counts)
#define PHASE_ACCUM_SHIFT                     23    // bits to right-shift phase to get 9-bit table index

// ── SYMMETRY WARP ────────────────────────────────────────────────────────────
// Fractional bits used for the two piecewise-linear warp slopes.  The largest
// slope is 128 (symmetry at one extreme), so 128 << 24 == 2^31 still fits in a
// uint32_t with room to spare.
#define WARP_SLOPE_FRAC_BITS 24

// Symmetry is an 8-bit control where 128 == centre == no warp.  0 and 256 are
// both degenerate (they ask one group to be traversed in zero time), so the
// value is clamped one step inside each end.
#define SYMMETRY_MIN 1
#define SYMMETRY_MAX 255

// ── PHASE OFFSET (SECONDARY OSCILLATOR) ──────────────────────────────────────
// The phase control is a 9-bit number where PHASE_POT_FULL_SCALE == 360 deg.
// It is fed by a 7-bit source (pot ADC, MIDI CC or preset) shifted up by 2, so
// the largest value it can actually take is PHASE_POT_CONTROL_MAX == 508,
// i.e. 357.19 deg - one 2.81 deg step short of wrapping back to 0 deg.
#define PHASE_POT_FULL_SCALE   (1UL << PHASE_ADC_RESOLUTION)          // 512
#define PHASE_POT_CONTROL_MAX  (PHASE_POT_FULL_SCALE - 4UL)           // 508
#define PHASE_OFFSET_SHIFT     (32 - PHASE_ADC_RESOLUTION)            // 23

// Set to ON if the phase pot is wired so that fully CW gives the LOW ADC
// reading.  Fully CCW must give 0 deg and fully CW must give ~360 deg.
#define PHASE_POT_REVERSED OFF


#if SINE_OR_TRIANGLE_WAVE_TEMPO_PERCEIVED_APEX_INDEX < SECOND_QUADRANT_START_INDEX
	#define CURRENT_QUADRANT_SINE_OR_TRI_SYNCED = FIRST_QUADRANT
	#define CURRENT_HALFCYCLE_SINE_OR_TRI_SYNCED = FIRST_HALFCYCLE

#elif SINE_OR_TRIANGLE_WAVE_TEMPO_PERCEIVED_APEX_INDEX < THIRD_QUADRANT_START_INDEX
	#define CURRENT_QUADRANT_SINE_OR_TRI_SYNCED = SECOND_QUADRANT
	#define CURRENT_HALFCYCLE_SINE_OR_TRI_SYNCED = FIRST_HALFCYCLE

#elif SINE_OR_TRIANGLE_WAVE_TEMPO_PERCEIVED_APEX_INDEX < FOURTH_QUADRANT_START_INDEX
	#define CURRENT_QUADRANT_SINE_OR_TRI_SYNCED FIRST_QUADRANT
	#define CURRENT_HALFCYCLE_SINE_OR_TRI_SYNCED SECOND_HALFCYCLE

#elif SINE_OR_TRIANGLE_WAVE_TEMPO_PERCEIVED_APEX_INDEX <= FINAL_INDEX
	#define CURRENT_QUADRANT_SINE_OR_TRI_SYNCED = SECOND_QUADRANT
	#define CURRENT_HALFCYCLE_SINE_OR_TRI_SYNCED = SECOND_HALFCYCLE
#endif


#if SQUARE_WAVE_TEMPO_APEX_INDEX < SECOND_QUADRANT_START_INDEX
	#define CURRENT_QUADRANT_SQUARE_SYNCED = FIRST_QUADRANT
	#define CURRENT_HALFCYCLE_SQUARE_SYNCED = FIRST_HALFCYCLE

#elif SQUARE_WAVE_TEMPO_APEX_INDEX < THIRD_QUADRANT_START_INDEX
	#define CURRENT_QUADRANT_SQUARE_SYNCED = SECOND_QUADRANT
	#define CURRENT_HALFCYCLE_SQUARE_SYNCED = FIRST_HALFCYCLE

#elif SQUARE_WAVE_TEMPO_APEX_INDEX < FOURTH_QUADRANT_START_INDEX
	#define CURRENT_QUADRANT_SQUARE_SYNCED FIRST_QUADRANT
	#define CURRENT_HALFCYCLE_SQUARE_SYNCED SECOND_HALFCYCLE

#elif SQUARE_WAVE_TEMPO_APEX_INDEX <= FINAL_INDEX
	#define CURRENT_QUADRANT_SQUARE_SYNCED = SECOND_QUADRANT
	#define CURRENT_HALFCYCLE_SQUARE_SYNCED = SECOND_HALFCYCLE

#endif

#define FIRST_SYNC_COMPLETE (0b1 << 3)
#define INITIAL_ADC_CONVERSION_COMPLETE (0b1 << 4)

#endif /* OSCILLATOR_MACROS_H_ */
